# encoding: UTF-8
module TranTuanNoiThat
  module CadWallsUI
    def self.html
      <<'TT_CAD_WALLS_HTML_END'
<!doctype html><html lang="vi"><meta charset="utf-8"><title>TT Nhập CAD — Dựng tường</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#edf2f5;color:#203341;font:15px 'Segoe UI',sans-serif}header{padding:18px 22px;background:#15566a;color:white}h1{font-size:22px;margin:0 0 6px}h2{font-size:17px;margin:0 0 12px}main{padding:16px;display:grid;grid-template-columns:340px 1fr;gap:16px}section{background:white;border:1px solid #d4dfe4;border-radius:8px;padding:16px;margin-bottom:14px}button{border:0;border-radius:5px;background:#156779;color:white;padding:10px 13px;font:600 14px 'Segoe UI';cursor:pointer;margin:3px 3px 3px 0}button.secondary{background:#e1ebef;color:#234b59}button:disabled{opacity:.45;cursor:default}label{display:block;margin:10px 0 4px}input[type=number],input[type=text]{width:100%;padding:8px;border:1px solid #afc2cd;border-radius:4px;font:inherit}input[type=checkbox]{width:18px;height:18px;vertical-align:middle}small,.muted{color:#607684;font-size:13px;line-height:1.5}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}#status{padding:12px 20px;background:#fff1ce;line-height:1.5;white-space:pre-wrap}.scroll{max-height:230px;overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}td,th{padding:8px;text-align:left;border-bottom:1px solid #e3ebef}th{position:sticky;top:0;background:#eaf1f4}#plan{width:100%;height:310px;background:#f5f8fa;border:1px solid #d7e1e5}#plan polygon{cursor:pointer} .warning{color:#98500a}.actions{position:sticky;bottom:0;background:white;border-top:1px solid #c5d6de;padding:10px 16px}.actions strong{margin-right:14px}#empty{text-align:center;color:#657986;padding:16px}details{margin-top:12px}summary{cursor:pointer;font-weight:600}.extent{margin:8px 0;font-weight:600;color:#186074}
</style>
<header><h1>Nhập CAD · Dựng tường</h1><div>Đọc mặt bằng → duyệt lớp và đoạn tường → xem trước 3D → tạo khối</div></header>
<div id="status" role="status">Nhập DWG/DXF hoặc chọn bản CAD đang có trong model rồi bấm Quét vùng chọn.</div>
<main><div><section><h2>1. Bản vẽ nguồn</h2><button onclick="call('import_cad')">Nhập DWG / DXF</button><button class="secondary" onclick="call('scan_selected')">Quét vùng chọn</button><button class="secondary" onclick="call('cancel_job')">Dừng quét</button><p class="muted">Chọn riêng một mặt bằng nằm trên XY. CAD gốc được giữ nguyên. Nhập tệp cần bộ nhập CAD của SketchUp.</p></section>
<section><h2>2. Thông số dựng</h2><div class="row"><div><label>Cao tường (mm)</label><input id="height" type="number" value="2800" min="100"></div><div><label>Cao độ chân (mm)</label><input id="base" type="number" value="0"></div></div><label>Dày tường cần nhận diện (mm)</label><input id="widths" type="text" value="100;110;200;220;250"><small>Phân cách bằng dấu ; — bổ sung độ dày thực tế của bản vẽ.</small><div class="row"><div><label>Sai số (mm)</label><input id="tolerance" type="number" value="2" min="0.1" max="10" step="0.1"></div><div><label>Đoạn tối thiểu (mm)</label><input id="min_length" type="number" value="250" min="50"></div></div><label>Hệ số CAD → tường</label><input id="scale" type="number" value="1" min="0.000001" step="any"><small>Giữ 1 nếu CAD đúng mm. Hệ số chỉ áp dụng tường và preview, không đổi CAD gốc. Kiểm tra chiều dài từng đoạn trước khi tạo.</small><p><button onclick="recognize()">Nhận diện / Cập nhật preview</button></p></section>
<section><h2>3. Lớp đưa vào nhận diện</h2><div id="layers" class="scroll">Chưa quét CAD.</div><p class="muted">Chỉ tự tích lớp có tên tường/wall. Lớp chưa phân loại cần bạn chọn. Không tích DIM, hatch, nội thất hoặc lớp ký hiệu cửa.</p></section></div>
<div><section><h2>Mặt bằng kiểm tra</h2><svg id="plan" xmlns="http://www.w3.org/2000/svg" aria-label="Preview mặt bằng tường"></svg><div id="extent" class="extent"></div><small>Cam: sẽ dựng · Xám: đã bỏ chọn. Click đoạn trong hình hoặc tích trong danh sách. Preview 3D xuất hiện trong cửa sổ SketchUp.</small><div id="empty">Chưa có đoạn tường. Quét CAD và chọn lớp cần nhận diện.</div></section>
<section><h2>Đoạn tường nhận diện <span id="count"></span></h2><div class="scroll"><table><thead><tr><th>Dựng</th><th>Đoạn</th><th>Dài × dày (mm)</th><th>Lớp / kiểm tra</th></tr></thead><tbody id="walls"></tbody></table></div></section>
<section><h2>Ký hiệu / lớp cần kiểm tra</h2><div id="symbols" class="scroll muted">Chưa có dữ liệu.</div><details><summary>Phạm vi nhận diện hiện tại</summary><p class="muted">Nhận diện theo tên lớp/block và cặp nét song song có độ dày phù hợp. Cung gần 90° được đánh dấu là có thể là cửa đi. Giữ các khoảng ngắt giữa nét tường; chưa tự khoét cửa từ ký hiệu, chưa dựng cửa sổ, lanh tô, cầu thang hoặc đọc chữ DIM. Không suy ra vật liệu chỉ từ hatch. Tường cong và bản vẽ ảnh chưa hỗ trợ. Các đoạn được hợp nhất Solid, xóa đường nối đồng phẳng; góc vuông chỉ nối trong phạm vi nét CAD gốc.</p></details></section></div></main>
<div class="actions"><strong id="selected">0 đoạn được chọn</strong><button id="previewBtn" disabled onclick="call('preview')">Xem trước 3D</button><button id="createBtn" disabled onclick="call('create')">TẠO TƯỜNG</button><small>Một lần Undo cho lượt dựng</small></div>
<script>
let state={layers:[],walls:[],symbols:[]},needsUpdate=false;
function call(name,...args){if(window.sketchup&&typeof window.sketchup[name]==='function')window.sketchup[name](...args);else setStatus('Cần mở bảng này từ công cụ trong SketchUp.');}
function setStatus(s){document.getElementById('status').textContent=s;}
function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
function recognize(){needsUpdate=false;const d={};['height','base','widths','tolerance','min_length','scale'].forEach(k=>d[k]=document.getElementById(k).value);d.layers=Array.from(document.querySelectorAll('#layers input:checked')).map(x=>x.value);call('recognize',JSON.stringify(d));}
function toggle(w){call('toggle_wall',w.id,!w.selected);}
function receive(d){state=d;const layers=document.getElementById('layers');layers.textContent='';d.layers.forEach(l=>{const row=el('label');const cb=el('input');cb.type='checkbox';cb.value=l.name;cb.checked=l.use;cb.onchange=dirty;row.appendChild(cb);row.appendChild(document.createTextNode(' '+l.name+' ('+l.count+')'));row.appendChild(el('small',' · '+l.kind));layers.appendChild(row);});
const table=document.getElementById('walls');table.textContent='';d.walls.forEach(w=>{const tr=el('tr');const td=el('td');const cb=el('input');cb.type='checkbox';cb.checked=w.selected;cb.onchange=()=>toggle(w);td.appendChild(cb);tr.appendChild(td);tr.appendChild(el('td',String(w.id+1)));tr.appendChild(el('td',w.length.toFixed(1)+' × '+w.width.toFixed(1)));tr.appendChild(el('td',w.layer+(w.warning?' · '+w.warning:'')));table.appendChild(tr);});
const n=d.walls.filter(w=>w.selected).length;document.getElementById('selected').textContent=n+' đoạn được chọn';document.getElementById('count').textContent='('+d.walls.length+')';document.getElementById('previewBtn').disabled=!n||needsUpdate;document.getElementById('createBtn').disabled=!n||needsUpdate;document.getElementById('empty').style.display=d.walls.length?'none':'block';
const symbols=document.getElementById('symbols');symbols.textContent='';d.symbols.forEach(s=>symbols.appendChild(el('p',s.name+' — '+s.kind+' ('+s.count+')')));if(!d.symbols.length)symbols.textContent='Không có ký hiệu được phân loại. Điều này không có nghĩa bản vẽ không có cửa.';drawPlan(d.walls);}
function drawPlan(walls){const svg=document.getElementById('plan');svg.textContent='';document.getElementById('extent').textContent='';if(!walls.length)return;const all=[];walls.forEach(w=>{const dx=w.b[0]-w.a[0],dy=w.b[1]-w.a[1],len=Math.hypot(dx,dy),nx=-dy/len*w.width/2,ny=dx/len*w.width/2;w.poly=[[w.a[0]-nx,w.a[1]-ny],[w.b[0]-nx,w.b[1]-ny],[w.b[0]+nx,w.b[1]+ny],[w.a[0]+nx,w.a[1]+ny]];all.push(...w.poly);});const xmin=Math.min(...all.map(p=>p[0])),xmax=Math.max(...all.map(p=>p[0])),ymin=Math.min(...all.map(p=>p[1])),ymax=Math.max(...all.map(p=>p[1]));const pad=Math.max(xmax-xmin,ymax-ymin)*.06+1;svg.setAttribute('viewBox',[xmin-pad,-ymax-pad,xmax-xmin+2*pad,ymax-ymin+2*pad].join(' '));walls.forEach(w=>{const p=document.createElementNS('http://www.w3.org/2000/svg','polygon');p.setAttribute('points',w.poly.map(v=>v[0]+','+(-v[1])).join(' '));p.setAttribute('fill',w.selected?'#efb77e':'#d5dfe4');p.setAttribute('stroke',w.selected?'#995b27':'#8998a0');p.setAttribute('stroke-width','1');p.setAttribute('vector-effect','non-scaling-stroke');p.onclick=()=>toggle(w);const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent='Tường '+(w.id+1)+': '+w.length.toFixed(1)+' × '+w.width.toFixed(1)+' mm';p.appendChild(title);svg.appendChild(p);});document.getElementById('extent').textContent='Phạm vi nhận diện: '+(xmax-xmin).toFixed(0)+' × '+(ymax-ymin).toFixed(0)+' mm';}
function dirty(){needsUpdate=true;document.getElementById('createBtn').disabled=true;document.getElementById('previewBtn').disabled=true;setStatus('Thông số đã đổi. Bấm Nhận diện / Cập nhật preview trước khi tạo.');}
window.addEventListener('DOMContentLoaded',()=>{['height','base','widths','tolerance','min_length','scale'].forEach(k=>document.getElementById(k).addEventListener('input',dirty));call('ready');});
</script></html>

TT_CAD_WALLS_HTML_END
    end
  end
end
