# encoding: UTF-8
module TranTuanNoiThat
  module CadWallsUI
    def self.html
      <<'TT_CAD_WALLS_HTML_END'
<!doctype html><html lang="vi"><meta charset="utf-8"><title>TT Nhập CAD — Dựng tường</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#edf2f5;color:#203341;font:15px 'Segoe UI',sans-serif}header{padding:18px 22px;background:#15566a;color:white}h1{font-size:22px;margin:0 0 6px}h2{font-size:17px;margin:0 0 12px}main{padding:16px;display:grid;grid-template-columns:340px 1fr;gap:16px}section{background:white;border:1px solid #d4dfe4;border-radius:8px;padding:16px;margin-bottom:14px}button{border:0;border-radius:5px;background:#156779;color:white;padding:10px 13px;font:600 14px 'Segoe UI';cursor:pointer;margin:3px 3px 3px 0}button.secondary{background:#e1ebef;color:#234b59}button:disabled{opacity:.45;cursor:default}label{display:block;margin:10px 0 4px}input[type=number],input[type=text]{width:100%;padding:8px;border:1px solid #afc2cd;border-radius:4px;font:inherit}input[type=checkbox]{width:18px;height:18px;vertical-align:middle}small,.muted{color:#607684;font-size:13px;line-height:1.5}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}#status{padding:12px 20px;background:#fff1ce;line-height:1.5;white-space:pre-wrap}.scroll{max-height:230px;overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}td,th{padding:8px;text-align:left;border-bottom:1px solid #e3ebef}th{position:sticky;top:0;background:#eaf1f4}#plan{width:100%;height:310px;background:#f5f8fa;border:1px solid #d7e1e5}#plan polygon{cursor:pointer} .warning{color:#98500a}.actions{position:sticky;bottom:0;background:white;border-top:1px solid #c5d6de;padding:10px 16px}.actions strong{margin-right:14px}#empty{text-align:center;color:#657986;padding:16px}details{margin-top:12px}summary{cursor:pointer;font-weight:600}.extent{margin:8px 0;font-weight:600;color:#186074}
</style><style id="tt-blue-white-theme">/*TT_BLUE_WHITE_THEME_v1*/:root{--bg:#06182d;--panel:#0b2748;--blue:#1677e8;--white:#f7fbff;--muted:#b9d8f5;--border:#2d6ea7}html,body{background:var(--bg)!important;color:var(--white)!important}body{font-family:Arial,"Segoe UI",sans-serif!important}h1,h2,h3,h4,h5,h6,label,legend,strong,b,.title,.name{color:#fff!important}p,.muted,.hint,.sub,.note,.help,.desc,.description,.small{color:var(--muted)!important}a{color:#8dccff!important}.top,.header,.head,.titlebar,.page-header,.app-header,.hero,.banner,.brand,.header-bar{background:linear-gradient(135deg,#0a4f9b,#147ce5)!important;color:#fff!important;border-color:#51a9ff!important}.panel,.card,.box,.section,.group,.pane,.sidebar,.content,.settings-card,.toolbar,.controls,.form-section,.block,.item,.row-card{background:var(--panel)!important;color:#fff!important;border-color:var(--border)!important}button,.btn,input[type=button],input[type=submit]{background:linear-gradient(180deg,#2188f3,#0c63be)!important;color:#fff!important;border:1px solid #53aaff!important;border-radius:7px!important}.primary,.go,.active,.selected,.danger,.warning,.secondary{background:#0f75dc!important;color:#fff!important;border-color:#68b8ff!important}input,select,textarea{background:#071d35!important;color:#fff!important;border:1px solid #3f7fb5!important;border-radius:6px!important}table{background:#09223f!important;color:#fff!important;border-color:#2c6595!important}th{background:#0e4f8d!important;color:#fff!important;border-color:#397caf!important}td{border-color:#244f74!important;color:#eaf5ff!important}tr:nth-child(even){background:#0a294a!important}tr:hover{background:#123d68!important}.badge,.pill,.tag,.chip{background:#0d5fae!important;color:#fff!important;border-color:#61b3ff!important}.ok,.success{color:#a9d9ff!important}.err,.error{color:#ffd9eb!important}hr{border-color:#2c628f!important}</style>
<header><h1>Nhập CAD · Dựng tường</h1><div>Đọc mặt bằng → duyệt lớp và đoạn tường → xem trước 3D → tạo khối</div></header>
<div id="status" role="status">Chọn CAD để quét riêng; không chọn sẽ quét toàn bộ ngữ cảnh hiện tại. Bấm Tự quét đường bao.</div>
<main><div><section><h2>1. Bản vẽ nguồn</h2><button onclick="call('import_cad')">Nhập DWG / DXF</button><button class="secondary" onclick="call('scan_selected')">Tự quét đường bao</button><button class="secondary" onclick="call('cancel_job')">Dừng quét</button><p class="muted">Tự nhận diện sau khi quét. Chỉ đọc đối tượng đang hiện trong ngữ cảnh hiện tại, trên mặt phẳng XY. CAD gốc được giữ nguyên. Nhập tệp cần bộ nhập CAD của SketchUp.</p></section>
<section><h2>2. Thông số dựng</h2><div class="row"><div><label>Cao tường (mm)</label><input id="height" type="number" value="2800" min="100"></div><div><label>Cao độ chân (mm)</label><input id="base" type="number" value="0"></div></div><label>Dày tường cần nhận diện (mm)</label><input id="widths" type="text" value="100;110;180;200;220;250"><small>Phân cách bằng dấu ; — bổ sung độ dày thực tế của bản vẽ.</small><div class="row"><div><label>Sai số (mm)</label><input id="tolerance" type="number" value="2" min="0.1" max="10" step="0.1"></div><div><label>Đoạn tối thiểu (mm)</label><input id="min_length" type="number" value="50" min="50"></div></div><label>Hệ số CAD → tường</label><input id="scale" type="number" value="1" min="0.000001" step="any"><small>Giữ 1 nếu CAD đúng mm. Hệ số chỉ áp dụng tường và preview, không đổi CAD gốc. Kiểm tra chiều dài từng đoạn trước khi tạo.</small><p><button onclick="recognize()">Nhận diện / Cập nhật preview</button></p></section>
<section><h2>3. Lớp đưa vào nhận diện</h2><div id="layers" class="scroll">Chưa quét CAD.</div><button class="secondary" onclick="call('save_rules',JSON.stringify(roles()))">Lưu quy tắc phân loại</button><p class="muted">Chọn vai trò từng lớp. Chỉ lớp Tường được đưa vào ghép nét. GUIDE/VECTOR cần kiểm tra. Quy tắc lưu theo tên lớp trên máy này.</p></section></div>
<div><section><h2>Mặt bằng kiểm tra</h2><label><input id="manual" type="checkbox" onchange="start=null;setStatus(this.checked?'Click hai đầu TIM tường trên nền CAD. ESC hủy điểm đầu. Không nối qua khoảng cửa.':'Đã tắt thêm theo tim.');"> Thêm theo tim tường (2 điểm)</label><div class="row"><div><label>Dày đoạn thêm (mm)</label><input id="manualWidth" type="number" value="220" min="30" max="2000"></div><div><label><input id="ortho" type="checkbox" checked> Khóa ngang/dọc</label><label><input id="sourceVisible" type="checkbox" checked onchange="drawPlan(state.walls)"> Hiện nét CAD</label></div></div><svg id="plan" xmlns="http://www.w3.org/2000/svg" aria-label="Preview mặt bằng tường"></svg><div id="extent" class="extent"></div><small>Cam: sẽ dựng · Xám: đã bỏ chọn · Nét mảnh: CAD nguồn (tối đa 20.000 nét). Lăn chuột zoom; kéo chuột phải di chuyển hình. Click đoạn trong hình hoặc tích trong danh sách. Preview 3D xuất hiện trong cửa sổ SketchUp.</small><div id="empty">Chưa có đoạn tường. Quét CAD và chọn lớp cần nhận diện.</div></section>
<section><h2>Đoạn tường nhận diện <span id="count"></span></h2><div class="scroll"><table><thead><tr><th>Dựng</th><th>Đoạn</th><th>Dài × dày (mm)</th><th>Lớp / kiểm tra</th></tr></thead><tbody id="walls"></tbody></table></div></section>
<section><h2>Đối chiếu độ dày</h2><div id="evidence" class="muted">Chưa phân tích.</div><p class="muted">Khoảng cách giữa nét song song dài ≥500 mm, làm tròn 1 mm. Chỉ là gợi ý; đồ nội thất cũng có thể tạo cặp nét. Lớp Tường: bổ sung độ dày có ít nhất hai cặp nét làm bằng chứng; kiểm tra preview trước khi dựng.</p></section><section><h2>Ký hiệu / lớp cần kiểm tra</h2><div id="symbols" class="scroll muted">Chưa có dữ liệu.</div><details><summary>Phạm vi nhận diện hiện tại</summary><p class="muted">Nhận đường bao vuông góc L/T (kể cả xoay), giữ phần lõm; nhận đường bao kín dạng dài, hẹp (dày 60–500 mm, dài tối thiểu 500 mm, dài/dày ≥4), giữ nguyên biên; cặp nét song song dùng độ dày đã nhập. Lớp chưa rõ chỉ gợi ý, cần tích xác nhận. Biên hở không được tự đóng; tường cong chưa hỗ trợ. Cặp nét trên lớp chưa rõ được gợi ý theo độ dày đo được, dài ≥1000 mm và dài/dày ≥5; phải xác nhận trước khi dựng. Cung gần 90° được đánh dấu là có thể là cửa đi. Giữ các khoảng ngắt giữa nét tường; chưa tự khoét cửa từ ký hiệu, chưa dựng cửa sổ, lanh tô, cầu thang hoặc đọc chữ DIM. Không suy ra vật liệu chỉ từ hatch. Tường cong và bản vẽ ảnh chưa hỗ trợ. Các đoạn được hợp nhất Solid, xóa đường nối đồng phẳng; góc vuông chỉ nối trong phạm vi nét CAD gốc.</p></details></section></div></main>
<div class="actions"><strong id="selected">0 đoạn được chọn</strong><button id="previewBtn" disabled onclick="call('preview')">Xem trước 3D</button><button id="createBtn" disabled onclick="call('create')">TẠO TƯỜNG</button><small>Một lần Undo cho lượt dựng</small></div>
<script>
let state={layers:[],walls:[],symbols:[],raw:[]},needsUpdate=false,start=null;
function call(name,...args){if(window.sketchup&&typeof window.sketchup[name]==='function')window.sketchup[name](...args);else setStatus('Cần mở bảng này từ công cụ trong SketchUp.');}
function setStatus(s){document.getElementById('status').textContent=s;}
function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
function roles(){const r={};document.querySelectorAll('#layers select').forEach(x=>r[x.dataset.name]=x.value);return r;}
function recognize(){start=null;needsUpdate=false;const d={};['height','base','widths','tolerance','min_length','scale'].forEach(k=>d[k]=document.getElementById(k).value);d.roles=roles();d.layers=Object.keys(d.roles).filter(k=>d.roles[k]==='Tường');call('recognize',JSON.stringify(d));}
function toggle(w){call('toggle_wall',w.id,!w.selected);}
function receive(d){state=d;const layers=document.getElementById('layers');layers.textContent='';d.layers.forEach(l=>{const row=el('label');row.appendChild(el('span',l.name+' ('+l.count+') '));const sel=el('select');sel.dataset.name=l.name;['Tường','Cửa đi','Cửa sổ','Cột','Nội thất','Bỏ qua','Chưa rõ'].forEach(v=>{const o=el('option',v);o.value=v;sel.appendChild(o);});sel.value=l.role||(l.use?'Tường':'Chưa rõ');sel.onchange=dirty;row.appendChild(sel);row.appendChild(el('small',' · '+l.kind));layers.appendChild(row);});
const table=document.getElementById('walls');table.textContent='';d.walls.forEach(w=>{const tr=el('tr');const td=el('td');const cb=el('input');cb.type='checkbox';cb.checked=w.selected;cb.onchange=()=>toggle(w);td.appendChild(cb);tr.appendChild(td);tr.appendChild(el('td',String(w.id+1)));tr.appendChild(el('td',w.length.toFixed(1)+' × '+w.width.toFixed(1)));tr.appendChild(el('td',w.layer+(w.warning?' · '+w.warning:'')));table.appendChild(tr);});
const n=d.walls.filter(w=>w.selected).length;document.getElementById('selected').textContent=n+' đoạn được chọn';document.getElementById('count').textContent='('+d.walls.length+')';document.getElementById('previewBtn').disabled=!n||needsUpdate;document.getElementById('createBtn').disabled=!n||needsUpdate;document.getElementById('empty').style.display=d.walls.length?'none':'block';
document.getElementById('evidence').textContent=(d.evidence||[]).map(v=>v.width+' mm ('+v.count+' cặp)').join(' · ')||'Không có đủ bằng chứng trong lớp đã chọn. Có thể chỉ định tim tường trên nền CAD.';
const symbols=document.getElementById('symbols');symbols.textContent='';d.symbols.forEach(s=>symbols.appendChild(el('p',s.name+' — '+s.kind+' ('+s.count+')')));if(!d.symbols.length)symbols.textContent='Không có ký hiệu được phân loại. Điều này không có nghĩa bản vẽ không có cửa.';drawPlan(d.walls);}
function drawPlan(walls){const svg=document.getElementById('plan');svg.textContent='';document.getElementById('extent').textContent='';const source=document.getElementById('sourceVisible').checked?(state.raw||[]):[];const scale=state.scale||1;const all=source.flatMap(e=>[e.a.map(v=>v*scale),e.b.map(v=>v*scale)]);walls.forEach(w=>{const dx=w.b[0]-w.a[0],dy=w.b[1]-w.a[1],len=Math.hypot(dx,dy),nx=-dy/len*w.width/2,ny=dx/len*w.width/2;w.poly=w.outline||[[w.a[0]-nx,w.a[1]-ny],[w.b[0]-nx,w.b[1]-ny],[w.b[0]+nx,w.b[1]+ny],[w.a[0]+nx,w.a[1]+ny]];all.push(...w.poly);});if(!all.length)return;const xmin=Math.min(...all.map(p=>p[0])),xmax=Math.max(...all.map(p=>p[0])),ymin=Math.min(...all.map(p=>p[1])),ymax=Math.max(...all.map(p=>p[1]));const pad=Math.max(xmax-xmin,ymax-ymin)*.06+1;svg.setAttribute('viewBox',[xmin-pad,-ymax-pad,xmax-xmin+2*pad,ymax-ymin+2*pad].join(' '));if(source.length){const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',source.map(e=>'M'+(e.a[0]*scale)+','+(-e.a[1]*scale)+'L'+(e.b[0]*scale)+','+(-e.b[1]*scale)).join(' '));path.setAttribute('stroke','#89959c');path.setAttribute('stroke-width','0.6');path.setAttribute('fill','none');path.setAttribute('vector-effect','non-scaling-stroke');svg.appendChild(path);}walls.forEach(w=>{const p=document.createElementNS('http://www.w3.org/2000/svg','polygon');p.setAttribute('points',w.poly.map(v=>v[0]+','+(-v[1])).join(' '));p.setAttribute('fill',w.selected?'#efb77e':'#d5dfe4');p.setAttribute('stroke',w.selected?'#995b27':'#8998a0');p.setAttribute('stroke-width','1');p.setAttribute('vector-effect','non-scaling-stroke');p.onclick=()=>{if(!document.getElementById('manual').checked)toggle(w);};const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent='Tường '+(w.id+1)+': '+w.length.toFixed(1)+' × '+w.width.toFixed(1)+' mm';p.appendChild(title);svg.appendChild(p);});document.getElementById('extent').textContent='Phạm vi nhận diện: '+(xmax-xmin).toFixed(0)+' × '+(ymax-ymin).toFixed(0)+' mm';}
function dirty(){start=null;needsUpdate=true;document.getElementById('createBtn').disabled=true;document.getElementById('previewBtn').disabled=true;setStatus('Thông số đã đổi. Bấm Nhận diện / Cập nhật preview trước khi tạo.');}
const svg=document.getElementById('plan');
function planPoint(e){let p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;p=p.matrixTransform(svg.getScreenCTM().inverse());return [p.x,-p.y];}
svg.addEventListener('click',e=>{if(!document.getElementById('manual').checked)return;if(needsUpdate||!state.height){setStatus('Bấm Nhận diện / Cập nhật preview để xác nhận thông số trước.');return;}let p=planPoint(e);if(!start){start=p;setStatus('Đã chọn đầu tim. Click đầu còn lại; ESC hủy.');return;}if(document.getElementById('ortho').checked){if(Math.abs(p[0]-start[0])>=Math.abs(p[1]-start[1]))p[1]=start[1];else p[0]=start[0];}const a=start;start=null;call('manual_wall',JSON.stringify({a:a,b:p,width:document.getElementById('manualWidth').value}));});
svg.addEventListener('mousemove',e=>{const old=document.getElementById('guide');if(old)old.remove();if(!start)return;let p=planPoint(e);if(document.getElementById('ortho').checked){if(Math.abs(p[0]-start[0])>=Math.abs(p[1]-start[1]))p[1]=start[1];else p[0]=start[0];}const l=document.createElementNS('http://www.w3.org/2000/svg','line');l.id='guide';l.setAttribute('x1',start[0]);l.setAttribute('y1',-start[1]);l.setAttribute('x2',p[0]);l.setAttribute('y2',-p[1]);l.setAttribute('stroke','#e36327');l.setAttribute('stroke-width',2);l.setAttribute('vector-effect','non-scaling-stroke');l.style.pointerEvents='none';svg.appendChild(l);});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){start=null;const g=document.getElementById('guide');if(g)g.remove();}});
svg.addEventListener('wheel',e=>{e.preventDefault();const v=svg.viewBox.baseVal;if(!v.width)return;const p=planPoint(e),f=e.deltaY>0?1.15:1/1.15;if(v.width*f<10||v.width*f>1e8)return;svg.setAttribute('viewBox',[p[0]+(v.x-p[0])*f,-p[1]+(v.y+p[1])*f,v.width*f,v.height*f].join(' '));},{passive:false});
let pan=null;svg.addEventListener('contextmenu',e=>e.preventDefault());svg.addEventListener('pointerdown',e=>{if(e.button===2){pan={x:e.clientX,y:e.clientY};svg.setPointerCapture(e.pointerId);}});svg.addEventListener('pointermove',e=>{if(!pan)return;const v=svg.viewBox.baseVal,m=svg.getScreenCTM();v.x-=(e.clientX-pan.x)/m.a;v.y-=(e.clientY-pan.y)/m.d;pan={x:e.clientX,y:e.clientY};});svg.addEventListener('pointerup',()=>pan=null);
window.addEventListener('DOMContentLoaded',()=>{['height','base','widths','tolerance','min_length','scale'].forEach(k=>document.getElementById(k).addEventListener('input',dirty));call('ready');});
</script></html>

TT_CAD_WALLS_HTML_END
    end
  end
end
