# encoding: UTF-8
module TranTuanNoiThat
  module RenameUI
    def self.html
      <<~'TT_RENAME_HTML'
<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TT – Đổi Tên</title>
<style>*{box-sizing:border-box}body{font:14px Arial,sans-serif;background:#f3f5f8;color:#203345;margin:18px}h1{font-size:22px;margin:0 0 5px}p{line-height:1.5;margin:8px 0}button,input,select{font:inherit}button{padding:9px 12px;border:1px solid #b8c6d4;border-radius:5px;background:white;cursor:pointer}button.primary{background:#1769a9;color:white;border-color:#1769a9}button:disabled{opacity:.5;cursor:wait}input[type=text],select{width:100%;padding:9px;border:1px solid #b8c6d4;border-radius:5px;background:white}label{display:block;margin:9px 0}input[type=checkbox]{accent-color:#1769a9}.bar{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.bar label{margin:0}.layout{display:grid;grid-template-columns:minmax(520px,1.2fr) minmax(330px,1fr);gap:15px;margin-top:14px}.panel{background:white;border:1px solid #d9e1e8;border-radius:8px;padding:14px}.table-wrap{height:460px;overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}th{position:sticky;top:0;background:#eaf0f6;text-align:left}th,td{padding:9px 7px;border-bottom:1px solid #e4e9ef}tr{cursor:pointer}tr.active{background:#fff0dc}tr:hover{background:#edf5fc}.stats{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.stats span{padding:8px 12px;background:#e6eef6;border-radius:5px}.muted{color:#647587;font-size:12px}#shape{height:300px;background:#fff9f0;border:1px solid #f1dfc8;border-radius:6px;display:flex;align-items:center;justify-content:center}#shape svg{width:100%;height:100%}#error{color:#b22d28;min-height:20px;margin:10px 0}#message{color:#276b35}details{margin-top:14px;border-top:1px solid #dbe2e9;padding-top:10px}summary{cursor:pointer;font-weight:bold}.thickness button{margin:3px}#detail-name{font-weight:bold;margin:10px 0;overflow-wrap:anywhere}@media(max-width:900px){.layout{grid-template-columns:1fr}.table-wrap{height:330px}}</style>
<h1>ĐỔI TÊN · THỐNG KÊ CHI TIẾT</h1><p class="muted">Chọn Group/Component ngoài model rồi quét, hoặc quét toàn model. Bấm một dòng để chọn đối tượng và xem biên dạng 3D.</p>
<div class="bar"><button id="scan" class="primary" onclick="scan(false)">Quét vùng đang chọn</button><button id="scan-all" onclick="scan(true)">Quét toàn model</button><label><input id="only-leaf" type="checkbox" checked onchange="render()"> Chỉ hiện chi tiết cuối</label><button onclick="checkAll()">Chọn tất cả đang hiện</button><button onclick="checked.clear();render()">Bỏ chọn</button></div>
<div id="message">Chưa quét.</div><div id="error" role="alert"></div><div id="stats" class="stats"></div>
<div class="layout"><section class="panel"><input id="filter" type="text" placeholder="Tìm tên, Tag hoặc độ dày…" oninput="render()"><div class="table-wrap"><table><thead><tr><th>Chọn</th><th>Tên đối tượng</th><th>Loại</th><th>Tag</th><th>Dày ≈ mm</th></tr></thead><tbody id="rows"></tbody></table></div><p id="selected-count"></p><div class="bar"><button onclick="page=Math.max(0,page-1);render()">Trang trước</button><span id="page-info"></span><button onclick="page++;render()">Trang sau</button></div><div id="thickness" class="thickness"></div><p class="muted">Độ dày ước tính = cạnh nhỏ nhất của hộp bao theo trục cục bộ, có tính scale; thống kê làm tròn 0,1 mm. Khối xoay hình học trong Group hoặc không phải tấm có thể cần kiểm tra lại.</p></section>
<section class="panel"><div class="bar"><b>Biên dạng 3D</b><button onclick="resetView()">Góc nhìn ban đầu</button></div><div id="detail-name">Chọn một đối tượng</div><div id="shape"><canvas id="view3d" width="700" height="420" style="width:100%;height:100%;touch-action:none;cursor:grab"></canvas></div><p id="shape-note" class="muted"></p><p id="dimensions"></p>
<label>Tên mới<input id="new-name" type="text" maxlength="120" placeholder="Ví dụ: Hậu phủ"></label><label><input id="change-tag" type="checkbox"> Đổi Tag cùng lượt lưu</label><label>Tên Tag mới (trống = Untagged)<input id="new-tag" type="text" maxlength="120"></label><div class="bar"><button class="primary action" onclick="save(false)">Lưu tên</button><button class="action" onclick="save(true)">Lưu & chi tiết tiếp</button></div>
<details><summary>Xóa tên / thay tên hàng loạt</summary><p>Áp dụng cho các dòng đã đánh dấu. Nhóm cha chỉ được chọn khi bỏ “Chỉ hiện chi tiết cuối”.</p><label>Tên thay thế sau khi xóa (trống = không tên)<input id="reset-name" type="text" maxlength="120"></label><label>Tag mặc định sau khi xóa (trống = Untagged)<input id="reset-tag" type="text" maxlength="120"></label><button class="action" onclick="clearNames()">Xóa / thay tên các dòng đã chọn</button></details><p class="muted">Đổi tên Component là đổi tên instance, giữ tên definition. Mỗi lượt lưu hoặc xóa có một lần Undo. Bấm dòng lồng nhau sẽ mở nhóm cha để chọn đúng chi tiết.</p></section></div>
<script>
let page=0;let rows=[],checked=new Set(),active=null,nextAfter=false,busy=false;
const el=id=>document.getElementById(id);
function showError(s){el('error').textContent=s;}
function scan(all){checked.clear();active=null;sketchup.scan(all);}
function scanState(s){busy=s.busy;el('message').textContent=s.message;document.querySelectorAll('.action,#scan,#scan-all').forEach(b=>b.disabled=busy);}
function visible(){let q=el('filter').value.toLocaleLowerCase();return rows.filter(r=>(!el('only-leaf').checked||r.leaf)&&(!q||[r.name,r.tag,r.thickness].join(' ').toLocaleLowerCase().includes(q)));}
function render(){let list=visible();page=Math.min(page,Math.max(0,Math.ceil(list.length/200)-1));el('page-info').textContent='Trang '+(page+1)+' / '+Math.max(1,Math.ceil(list.length/200));let body=el('rows');body.innerHTML='';list.slice(page*200,page*200+200).forEach(r=>{let tr=document.createElement('tr');tr.className=r.id===active?'active':'';let td=document.createElement('td'),c=document.createElement('input');c.type='checkbox';c.checked=checked.has(r.id);c.onclick=e=>{e.stopPropagation();c.checked?checked.add(r.id):checked.delete(r.id);el('selected-count').textContent='Đã chọn '+checked.size+' đối tượng';};td.appendChild(c);tr.appendChild(td);[r.name||'(Không tên)',r.type+(r.leaf?'':' · Cụm'),r.tag,r.thickness===null?'—':r.thickness].forEach(v=>{let t=document.createElement('td');t.textContent=v;tr.appendChild(t);});tr.onclick=()=>{checked=new Set([r.id]);active=r.id;render();sketchup.choose(r.id);};body.appendChild(tr);});el('selected-count').textContent='Đã chọn '+checked.size+' / '+visible().length+' dòng đang hiện';}
function setRows(data){rows=data.rows;checked=new Set([...checked].filter(id=>rows.some(r=>r.id===id)));scanState({busy:false,message:'Quét xong. Chọn đối tượng để đổi tên.'});let s=data.summary;el('stats').innerHTML='';['Tổng đối tượng: '+s.total,'Chi tiết cuối: '+s.details,'Cụm / khác: '+s.assemblies,'Số độ dày: '+s.thickness.length].forEach(t=>{let n=document.createElement('span');n.textContent=t;el('stats').appendChild(n);});el('thickness').innerHTML='';s.thickness.forEach(t=>{let b=document.createElement('button');b.textContent=t.value+' mm: '+t.count+' chi tiết';b.onclick=()=>{checked=new Set(rows.filter(r=>r.leaf&&Math.round(r.thickness*10)/10===t.value).map(r=>r.id));el('filter').value='';el('only-leaf').checked=true;render();};el('thickness').appendChild(b);});render();}
function selectRows(ids){checked=new Set(ids);if(ids[0]){active=ids[0];let r=rows.find(x=>x.id===active);if(r&&!r.leaf)el('only-leaf').checked=false;el('filter').value='';page=Math.max(0,Math.floor(visible().findIndex(x=>x.id===active)/200));}render();}
function showDetail(r){active=r.id;el('detail-name').textContent=(r.name||'(Không tên)')+(r.locked?' · ĐANG KHÓA':'')+(r.shared?' · Nhóm cha có bản sao':'');setGeometry(r);el('shape-note').textContent=r.note;el('dimensions').textContent='Kích thước X × Y × Z: '+r.dims.join(' × ')+' mm';el('new-name').value=r.name;el('new-tag').value=r.tag;render();}

function checkAll(){visible().forEach(r=>checked.add(r.id));render();}
function save(next){if(!checked.size){showError('Chọn đối tượng trước khi lưu.');return;}let list=visible(),index=list.findIndex(r=>r.id===active);nextAfter=next&&list[index+1]?list[index+1].id:false;showError('');sketchup.save(JSON.stringify({ids:[...checked],name:el('new-name').value,tag:el('new-tag').value,change_tag:el('change-tag').checked}));}
function clearNames(){if(!checked.size){showError('Chọn các dòng cần xóa tên.');return;}nextAfter=false;showError('');sketchup.clear_names(JSON.stringify({ids:[...checked],name:el('reset-name').value,tag:el('reset-tag').value}));}
function saved(s){showError('');el('message').textContent=s.message;if(nextAfter){let id=nextAfter;nextAfter=false;if(rows.some(r=>r.id===id)){checked=new Set([id]);active=id;render();sketchup.choose(id);}}}
let geometry={lines:[],faces:[]},yaw=-0.6,pitch=0.45,zoom=1,drag=null;
const cv=el('view3d'),cx=cv.getContext('2d');
function resetView(){yaw=-0.6;pitch=0.45;zoom=1;draw3d();}
function setGeometry(r){let changed=geometry.id!==r.id;geometry=r;if(changed)resetView();else draw3d();}
function draw3d(){cx.clearRect(0,0,700,420);let points=[].concat(...geometry.lines,...geometry.faces);if(!points.length){cx.fillStyle='#647587';cx.font='18px Arial';cx.fillText('Chọn đối tượng để xem 3D',200,210);return;}
let low=[Infinity,Infinity,Infinity],high=[-Infinity,-Infinity,-Infinity];points.forEach(p=>p.forEach((v,i)=>{low[i]=Math.min(low[i],v);high[i]=Math.max(high[i],v);}));let mid=low.map((v,i)=>(v+high[i])/2),scale=zoom*330/Math.max(1,Math.hypot(...high.map((v,i)=>v-low[i])));
function project(p){let x=p[0]-mid[0],y=p[1]-mid[1],z=p[2]-mid[2],a=x*Math.cos(yaw)-y*Math.sin(yaw),b=x*Math.sin(yaw)+y*Math.cos(yaw);return [350+a*scale,210-(z*Math.cos(pitch)-b*Math.sin(pitch))*scale,z*Math.sin(pitch)+b*Math.cos(pitch)];}
let triangles=geometry.faces.map(f=>f.map(project));triangles.sort((a,b)=>a.reduce((s,p)=>s+p[2],0)-b.reduce((s,p)=>s+p[2],0));triangles.forEach(f=>{let a=f[1].map((v,i)=>v-f[0][i]),b=f[2].map((v,i)=>v-f[0][i]),n=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len=Math.hypot(...n)||1,shade=0.7+0.3*Math.abs(n[2])/len;cx.beginPath();f.forEach((p,i)=>i?cx.lineTo(p[0],p[1]):cx.moveTo(p[0],p[1]));cx.closePath();cx.fillStyle='rgb('+[255,199,139].map(v=>Math.round(v*shade)).join(',')+')';cx.fill();});
cx.strokeStyle='rgba(119,77,36,0.65)';cx.lineWidth=0.8;cx.beginPath();geometry.lines.forEach(line=>{let a=project(line[0]),b=project(line[1]);cx.moveTo(a[0],a[1]);cx.lineTo(b[0],b[1]);});cx.stroke();}
cv.onpointerdown=e=>{drag=[e.clientX,e.clientY];cv.setPointerCapture(e.pointerId);};cv.onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*0.01;pitch+=(e.clientY-drag[1])*0.01;drag=[e.clientX,e.clientY];draw3d();};cv.onpointerup=cv.onpointercancel=()=>drag=null;cv.onwheel=e=>{e.preventDefault();zoom=Math.max(0.2,Math.min(5,zoom*(e.deltaY>0?0.9:1.1)));draw3d();};
window.addEventListener('load',()=>sketchup.ready());
</script></html>

TT_RENAME_HTML
    end
  end
end
