name: Build Co Gian Khoi MODE DEV

on:
  push:
    branches:
      - feature/co-gian-mode-v1

jobs:
  build-rbz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build RBZ
        run: |
          cd tran_tuan_noi_that_release/files
          zip -r ../../TRANTUAN_CO_GIAN_MODE_V0.1.0_TEST.rbz TranTuanNoiThat.rb tran_tuan_noi_that
      - uses: actions/upload-artifact@v4
        with:
          name: TRANTUAN_CO_GIAN_MODE_V0.1.0_TEST
          path: TRANTUAN_CO_GIAN_MODE_V0.1.0_TEST.rbz
